---
- name: create jenkins update directory
  file:
    path: "{{jenkins_home}}/updates"
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory
    recurse: yes
- name: install plugins
  command: >
        creates={{ jenkins_home }}/plugins/{{ item }}.jpi
        java -jar /{{ jenkins_home }}/jenkins-cli.jar -s http://localhost:{{jenkins_port}}/  install-plugin {{ item }}
  with_items: "{{ my_jenkins_plugins }}"

################################## using jenkins_pluin moduel#########################################################

#- name: plugings
#  jenkins_plugin:
#          name: "{{item.key}}"
#          state: "{{ 'enabled' if item.value['enabled'] else 'disabled'}}"
#  when: >
#    'enabled' in item.value
#  with_dict: "{{ my_jenkins_plugins }}"
