---
- hosts: localhost
  become: yes
  become_method: sudo
  remote_user: root
  tasks:
 
    - name: Installing jenkins yum repo
      get_url:
         url: https://pkg.jenkins.io/redhat/jenkins.repo
         dest: /etc/yum.repos.d/

    - name: Importing gpg key
      rpm_key:
         state: present
         key: https://pkg.jenkins.io/redhat/jenkins.io.key
         validate_certs: no

    - name: installing jenkins server
      yum:
        name: jenkins
        state: present
   
    - name: Make sure the plugin is always up-to-date
      jenkins_plugin:
         name: token-macro
         state: latest



#c9a911cbf10f9dde136a4b71e0c7fbb1






