---
- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    my_jenkins_params:
       url_username: admin
      # url_password: p4ssw0rd
      # url: http://localhost:8080
  tasks:
   
    - name: install git plugin
      jenkins_plugin:
         name: git
         state: latest
         params: "{{ my_jenkins_params }}"
         url_password: admin
       #  update_url: https://updates.jenkins-ci.org
         url: http://localhost:8080

#c9a911cbf10f9dde136a4b71e0c7fbb1






